{
    "openapi": "3.0.0",
    "info": {
        "title": "API da Aplicação E2E Burguer",
        "description": "API de comandas digitais para restaurantes e lanchonetes usada nos treinamentos de automação de testes da E2E Treinamentos",
        "contact": {
            "email": "professores@e2etreinamentos.com.br"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:3333",
            "description": "API de teste para desenvolvedores"
        },
        {
            "url": "https://e2etreinamentos.com/e2eburguer-api/v1",
            "description": "API de produção - Pendente de implementação"
        }
    ],
    "paths": {
        "/users": {
            "post": {
                "summary": "Cadastro de usuário",
                "description": "Essa rota é responsável pelo cadastro de um novo usuário",
                "tags": [
                    "Users"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Users"
                            },
                            "example": {
                                "name": "string",
                                "email": "string",
                                "password": "string"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Users"
                                },
                                "example": {
                                    "id": "string",
                                    "name": "string",
                                    "email": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Nome, e-mail e senha são obrigatórios.",
                                    "message": [                                       
                                        "Formato de e-mail inválido",
                                        "Senha inválida. A senha deve conter entre 8 e 12 caracteres, incluindo pelo menos uma letra maiúscula, um número e um caractere especial."
                                    ]
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "E-mail já cadastrado"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/session": {
            "post": {
                "summary": "Autenticação de usuário",
                "description": "Esta rota é responsável pela autenticação de um usuário existente",
                "tags": [
                    "Session"
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Session"
                            },
                            "example": {
                                "email": "string",
                                "password": "string"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/SessionResponse"
                                },
                                "example": {
                                    "id": "string",
                                    "name": "string",
                                    "email": "string",
                                    "token": "jwt_token"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "E-mail e senha são obrigatórios."
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Usuário e/ou Senha incorretos."
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                
                }
            }
        },
        "/user": {
            "delete": {
                "summary": "Remoção de usuário",
                "description": "Esta rota é responsável por remover um usuário existente",
                "tags": [
                    "Users"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "query",
                        "required": true,
                        "description": "ID do usuário a ser removido",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "required": true,
                "responses": {
                    "200": {
                        "description": "Usuário excluído com sucesso."
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "ID do usuário é necessário."
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Usuário não encontrado."
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/me": {
            "get": {
                "summary": "Detalhes de usuário",
                "description": "Esta rota é responsável por exibir os detalhes de um usuário",
                "tags": [
                    "Users"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "name": "user_id",
                        "in": "query",
                        "required": true,
                        "description": "ID do usuário a ser exibido dados",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "required": true,
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/UserDetail"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Usuário não encontrado."
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/category": {
            "post": {
                "summary": "Cadastrar categoria de produto",
                "description": "Esta rota é responsável por cadastrar uma categoria de produtos",
                "tags": [
                    "Category"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Category"
                            },
                            "example": {
                                "name": "string"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "description": "Created",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CategoryResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": [
                                        
                                        "Informe um nome válido para a categoria."
                                    ]
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "409": {
                        "description": "Categoria já cadastrada"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/category/remove": {
            "delete": {
                "summary": "Remoção de categoria",
                "description": "Esta rota é responsável por remover uma categoria de produto",
                "tags": [
                    "Category"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "parameters": [
                    {
                        "id": "category_id",
                        "in": "query",
                        "required": true,
                        "description": "ID da categoria a ser removido",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Category"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "ID da categoria é necessário."
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Categoria com o ID ${category_id} não encontrada"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/category/list": {
            "get": {
                "summary": "Listar categoria de produto",
                "description": "Esta rota é responsável por listar as categorias de produtos",
                "tags": [
                    "Category"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CategoryResponse"
                                },
                                "example": [
                                    {
                                        "id": "string",
                                        "name": "string"
                                    },
                                    {
                                        "id": "string",
                                        "name": "string"
                                    },
                                    {
                                        "id": "string",
                                        "name": "string"
                                    }
                                ]
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/product": {
            "post": {
                "summary": "Cadastro de Produto",
                "description": "Essa rota é responsável pelo cadastro de um novo produto, incluindo o upload de uma foto.",
                "tags": [
                    "Product"
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "schema": {
                                    "$ref": "#/components/schemas/Product"
                                },
                                "example": {
                                    "name": "string",
                                    "price": "string",
                                    "description": "string",
                                    "banner": "string",
                                    "category_id": "string"
                                },
                                "required": [
                                    "name",
                                    "price",
                                    "description",
                                    "banner",
                                    "category_id"
                                ]
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Produto cadastrado com sucesso"
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": [
                                        
                                        "Campos obrigatórios não preenchidos",
                                        "Erro no upload da foto"
                                    ]
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Categoria não encontrada"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "category/product": {
            "get": {
                "summary": "Listar categoria de produto",
                "description": "Esta rota é responsável por listar as categorias de produtos",
                "tags": [
                    "Product"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/CategoryResponse"
                                },
                                "example": [
                                    {
                                        "id": "string",
                                        "name": "string"
                                    },
                                    {
                                        "id": "string",
                                        "name": "string"
                                    },
                                    {
                                        "id": "string",
                                        "name": "string"
                                    }
                                ]
                            }
                        }
                    },
                    "400":{
                        "description": "category_id válido é obrigatório!"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal server error."
                    }
                }
            }
        },
        "/order": {
            "post": {
                "summary": "Cadastro de Pedido",
                "description": "Cadastra um novo pedido.",
                "tags": [
                    "Order"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Order"
                            },
                            "example": {
                                "table": 4,
                                "name": "string"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Pedido cadastrado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OrderResponse"
                                },
                                "example": {
                                    "id": "6282c26d-48c8-4963-baa2-4dff86915e82",
                                    "table": 4,
                                    "status": false,
                                    "draft": true,
                                    "name": "string",
                                    "created_at": "2023-12-19T22:13:49.754Z",
                                    "updated_at": "2023-12-19T22:13:49.754Z"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Erro de Solicitação",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Número da mesa inválido"
                                }
                            }
                        }
                    },
                    "422": {
                        "description": "Erro de Entidade Inconsistente",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Nome inválido"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Erro Interno do Servidor",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Erro ao criar o pedido"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/order/add": {
            "post": {
                "summary": "Adicionar item ao pedido",
                "description": "Adiciona um item a um pedido existente.",
                "tags": [
                    "Order"
                ],
                "security": [
                    {
                        "bearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/OrderItem"
                            },
                            "example": {
                                "order_id": "4c7fb257-9638-4226-995d-8f1ac175e552",
                                "product_id": "70f145b5-bf8f-49c8-b73e-13ae31b03d5f",
                                "amount": 2
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Item adicionado ao pedido com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OrderItemResponse"
                                },
                                "example": {
                                    "id": "90db0bf9-a7d1-4fc3-898c-d2eae691326b",
                                    "amount": 2,
                                    "created_at": "2023-12-06T14:12:14.460Z",
                                    "updated_at": "2023-12-06T14:12:14.460Z",
                                    "order_id": "4c7fb257-9638-4226-995d-8f1ac175e552",
                                    "product_id": "70f145b5-bf8f-49c8-b73e-13ae31b03d5f"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Todos os campos são necessários.",
                                    "message": [
                                        "A quantidade deve ser um número positivo."
                                        
                                    ]
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Bad Request",
                        "content": {
                            "application/json": {
                                "example": {
                                    "error": "Pedido não encontrado.",
                                    "message": [
                                        
                                        "Produto não encontrado."
                                    ]
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/order/detail": {
            "get": {
                "summary": "Detalhes do Pedido",
                "description": "Retorna os detalhes de um pedido específico.",
                "tags": [
                    "Order"
                ],
                "parameters": [
                    {
                        "name": "order_id",
                        "in": "query",
                        "required": true,
                        "description": "ID do pedido para obter detalhes",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OrderDetailResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "ID do pedido é necessário."
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Pedido não encontrado ou sem itens."
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "summary": "Listar Pedidos",
                "description": "Retorna uma lista de pedidos.",
                "tags": [
                    "Order"
                ],
                  "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/OrderResponse"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Não foi possível listar os pedidos."
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal server error."
                    }
                }
            }
        },
        "/order/send": {
            "put": {
                "summary": "Atualizar Status do Pedido",
                "description": "Atualiza o status de um pedido para enviado (não rascunho).",
                "tags": [
                    "Order"
                ],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/OrderRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Order"
                                },
                                "example": {
                                    "id": "985699ed-7a9a-42a1-a86a-c4923fc3bdc0",
                                    "table": 4,
                                    "status": false,
                                    "draft": false,
                                    "name": "string",
                                    "created_at": "2023-12-27T14:44:09.427Z",
                                    "updated_at": "2023-12-27T14:44:09.427Z"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "ID do pedido é necessário."
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Pedido não encontrado"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/order/finish": {
            "put": {
                "summary": "Finalizar Pedido",
                "description": "Finaliza um pedido, atualizando seu status para não ser mais um rascunho.",
                "tags": ["Order"],
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/OrderRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Pedido finalizado com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Order"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "ID do pedido é necessário."
                    },
                    "404": {
                        "description": "Pedido não encontrado"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/order/remove": {
            "delete": {
                "summary": "Remover Pedido",
                "description": "Remove um pedido existente pelo seu ID.",
                "tags": ["Order"],
                "parameters": [
                    {
                        "name": "order_id",
                        "in": "query",
                        "required": true,
                        "description": "Identificador único do pedido a ser removido",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Pedido removido com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Order"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "ID do pedido inválido"
                    },
                    "404": {
                        "description": "Pedido não encontrado"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        },
        "/order/remove/item": {
            "delete": {
                "summary": "Remover Item do Pedido",
                "description": "Remove um item específico de um pedido pelo seu ID.",
                "tags": ["Order"],
                "parameters": [
                    {
                        "name": "item_id",
                        "in": "query",
                        "required": true,
                        "description": "Identificador único do item a ser removido do pedido",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Item removido com sucesso",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Order"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "ID do item inválido ou não fornecido"
                    },
                    "404": {
                        "description": "Item não encontrado"
                    },
                    "500": {
                        "description": "Erro interno no servidor"
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "Users": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "UserDetail": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    }
                }
            },
            "Session": {
                "type": "object",
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                }
            },
            "SessionResponse": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "token": {
                        "type": "string",
                        "bearerFormat": "JWT"
                    }
                }
            },
            "Category": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "id": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string"
                    },
                    "updated_at": {
                        "type": "string"
                    }
                }
            },
            "CategoryResponse": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        }
                    }
                }
            },
            "ProductListResponse": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "price": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "banner": {
                            "type": "string"
                        },
                        "created_at": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "updated_at": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "category_id": {
                            "type": "string"
                        }
                    }
                }
            },
            "Product": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Nome do produto"
                    },
                    "price": {
                        "type": "string",
                        "description": "Preço do produto"
                    },
                    "description": {
                        "type": "string",
                        "description": "Descrição do produto"
                    },
                    "banner": {
                        "type": "string",
                        "format": "binary",
                        "description": "Foto do produto"
                    },
                    "category_id": {
                        "type": "string",
                        "description": "ID da categoria do produto"
                    }
                }
            },
            "Order": {
                "type": "object",
                "properties": {
                    "table": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string"
                    },
                    "draft": {
                        "type": "boolean"
                    },
                    "status": {
                        "type": "boolean",
                        "description": "Estado atual do pedido"
                    },
                    "id": {
                        "type": "string",
                        "description": "Identificador único do pedido"
                    }
                },
                "required": [
                    "table",
                    "name"
                ]
            },
            "OrderResponse": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "table": {
                        "type": "integer"
                    },
                    "status": {
                        "type": "boolean"
                    },
                    "draft": {
                        "type": "boolean"
                    },
                    "name": {
                        "type": "string"
                    },
                    "created_at": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updated_at": {
                        "type": "string",
                        "format": "date-time"
                    }
                }
            },
            "OrderItem": {
                "type": "object",
                "properties": {
                    "order_id": {
                        "type": "string"
                    },
                    "product_id": {
                        "type": "string"
                    },
                    "amount": {
                        "type": "integer"
                    }
                },
                "required": [
                    "order_id",
                    "product_id",
                    "amount"
                ]
            },
            "OrderItemResponse": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "amount": {
                        "type": "integer"
                    },
                    "created_at": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "updated_at": {
                        "type": "string",
                        "format": "date-time"
                    },
                    "order_id": {
                        "type": "string"
                    },
                    "product_id": {
                        "type": "string"
                    }
                }
            },
            "OrderDetailResponse": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "order_id": {
                        "type": "string"
                    },
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/OrderItem"
                        }
                    }
                }
            }
        },
        "securitySchemes": {
            "bearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    }
}